set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=leak" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g" CACHE STRING "" FORCE)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsanitize=leak" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g" CACHE STRING "" FORCE)

set(CMAKE_CXX_STANDARD 11)