#pragma once

#ifndef SPATIALSIM_MACHINEDEFINES_H_INCLUDED_
#define SPATIALSIM_MACHINEDEFINES_H_INCLUDED_

#define MAX_NUM_THREADS 96
#define CACHE_LINE_SIZE 64

#endif // SPATIALSIM_MACHINEDEFINES_H_INCLUDED_
