#pragma once

#ifndef SPATIALSIM_MACHINEDEFINES_H_INCLUDED_
#define SPATIALSIM_MACHINEDEFINES_H_INCLUDED_

#ifdef COUNTRY_US
#define MAX_NUM_THREADS 36
#else
#define MAX_NUM_THREADS 36
#endif
#define CACHE_LINE_SIZE 256

#endif // SPATIALSIM_MACHINEDEFINES_H_INCLUDED_
