name: clang-format

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.6
      with:
        source: './src'
        extensions: 'h,cpp,hpp'
        clangFormatVersion: 9
